# Site
repository: pritchyspritch/pritchyspritch.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Samuel Pritchard
title: Application Security and Penetration Testing
email: s.pritch@pm.me
website: pritchyspritch.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  pritchyspritch
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: spritchardsec
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-0YCGLQX2NT"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sam and I'm a Penetration Tester. I like testing systems for security issues, helping services build systems that are secure by design and writing code that makes our lives easier. I have worked for two organisations while I've been a pen tester and I have experience leading teams, managing testing schedules and developing penetration testing processes and documentation.

  I am most skilled in: <mark>AWS</mark>, <mark>Kali</mark> and <mark>Python</mark>
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: KidsLoop
        link: https://kidsloop.net/
        link_text: KidsLoop
        sub_title: Application Security Consultant
        caption: January 2022 - Present
        quote: >
          We aim to transform early years education by providing the tools and asset libraries to digitize content, collect data, and make a personalized learning path for every student.
        description: | # this will include new lines to allow paragraphs
            I began working for KidsLoop as their new Application Security Consultant to help them to test their applications and infrastructure for vulnerabilities and to provide security advice and threat modelling earlier on in the Secure Software Development Lifecycle. This included setting up the new Threat Modelling process as well as working with teams on creating code scanning options in GitHub Actions and providing advice to teams working on new product features. So far I have been:
           
            * developing and running the Threat Modelling process following STRIDE and DREAD
            * pen testing web applications 
            * developing GitHub Actions reusable workflows and templates to scan code/terraform/containers for vulnerabilities
            * automating reporting and scanning with scripts and APIs
            * assisting teams to fix misconfigurations/issues
            * contributing to the internal RFC processes
            * providing security guidance to internal teams

      - layout: left
        title: Cabinet Office | CDIO Cyber Security | Government Digital Service (GDS)
        link: www.gov.uk/government/organisations/cabinet-office
        link_text: GOV.UK
        sub_title: Ethical Hacker
        caption: January 2019 - January 2022
        quote: >
          We support the Prime Minister and ensure the effective running of government. We are also the corporate headquarters for government, in partnership with HM Treasury, and we take the lead in certain critical policy areas.
        description: | # this will include new lines to allow paragraphs
            I was first employed by GDS (Government Digital Service) in January 2019 as the sole Ethical Hacker in a multidisciplinary team. The scope of the team later expanded by merging the team into the [Cabinet Office CDIO (Chief Digital Information Office)](https://gds-way.cloudapps.digital/standards/cdio-pillars.html#cdio-security), our responsibilities expanding to the whole of the Cabinet Office, rather than just GDS. I became the technical lead for penetration testing in CDIO; scheduling tests, setting up the end-to-end processes, creating all of the team technical documentation, and leading a small team of testers.
            
            My team currently performs:
            * web application penetration tests
            * AWS security reviews
            * vulnerability scans (including for PCI compliance)
            * terraform code reviews
            * secure code reviews (languages include: Ruby, Python, GoLang, and Java)
            * review of the CI/CD pipelines and secret management
            * internal IT network penetration tests
            * assisting colleagues with finding issues in our SIEM and advising on attack methods
            * developing and editing scripts to improve our processes - examples of which include:
              * an [installed packages CVE evaluation script](https://github.com/pritchyspritch/active-cve-check) that I forked and edited to cut our PCI scanning time down by adding automatic package collection and personalised reporting.
              * a bash [script I hacked together](https://github.com/pritchyspritch/ecr-scanner) to download, build and scan AWS ECR container images with Trivy.

            During my time working with engineers, I also lead the development of our [Nessus scanner running in AWS, deployed by terraform and concourse CI/CD](https://github.com/alphagov/cyber-security-nessus), with all data automatically being sent to Splunk using our in-house log shipping tool.

            All our testing is done via our [Kali Linux testing machines deployed to AWS EC2 with terraform](https://github.com/alphagov/penetration-testing-instance), with our traffic from BurpSuite being tunneled through it also using SSH tunnels.

      - layout: left
        title: Dionach Ltd
        link: www.dionach.com
        link_text: Dionach
        sub_title: Penetration Tester
        caption: September 2016 - January 2019
        quote: >
          Dionach is an independent, CREST approved global provider of information security solutions.
        description: | # this will include new lines to allow paragraphs
            Dionach are a medium sized computer security company based in Oxford. They provide a wide range of security services to the public and private sector.

            Dionach trained me as a penetration tester, during my time with them I:

            * conducted a large number of penetration tests with detailed technical reports
            * had an above average success rate on social engineering campaigns (phishing and physical)
            * learned to use a wide range of security tools
            * learned to conduct tests using manual techniques with a proxy to intercept requests
            * lead the majority of tests but sometimes worked in a team to work on different areas of a larger project
            * carried out a large number of security audits on client sites including IT Health Checks and Cyber Essentials Plus

      - layout: left
        title: Prigital Ltd
        link: pritchyspritch.github.io
        link_text: Prigital
        sub_title: Self employed digital services provider
        caption: August 2019 - August 2020
        quote: >
          Prigital is a company I set up to allow me to provide web development services to a single client
        description: | # this will include new lines to allow paragraphs
            Prigital was set up to provide digital services to a single client in the shipping industry. I came in halfway through a project to develop it further, bring a sub-contractor on through my company and manage the delivery.

            We used:
            * Python and Django
            * AWS EC2, SES, and S3

  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of West London
        caption: 2012 - 2016
        sub_title: BSc (Hons) Computing Science - 1st Class
        quote: >
          The University of West London is a public research university in the United Kingdom which has campuses in Ealing and Brentford in Greater London, as well as in Reading, Berkshire. The university has roots back to 1860, when the Lady Byron School was founded, which later became Ealing College of Higher Education.
        description: | # this will include new lines to allow paragraphs
          During my time at UWL, I learned the basics of computing and programming. It was in my security module, however, that I learned about the different career opportunities available in cyber security.

          My dissertation was on Blockchain and Accounting Software Usability.

          Our modules includes:
          - Algorithms and Data Structures
          - Database Design and Management
          - Computer Security
          - Distributed Systems
          - Internet Technologies
          - Knowledge Based Systems
          - Object Oriented Modelling and Programming.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in security and software engineering some of my other interests and hobbies are:
      - Gaming
      - Travelling
      - Eating out

      I can also speak intermediate level Brazilian Portuguese.
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
