# Site
repository: pritchyspritch/pritchyspritch.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Samuel Pritchard
title: Security Engineer
email: sam@prigital.co.uk
website: www.prigital.co.uk

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  pritchyspritch
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: spritchardsec
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-0YCGLQX2NT"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sam and I'm a Security Engineer. I like testing systems for security issues with my experience in pen testing, helping digital services to build systems that are secure by design and writing code to automate my workflows. I have worked for a number of organisations while I've been a pen tester and app sec engineer. I have experience leading teams and managing testing schedules as well as developing processes and documentation for application security and penetration testing. I also have experience building automation in GitHub Actions such as reusable workflows, and composite actions. I've built tools using python and terraform deployed to AWS and Azure, and I'm currently at the beginning of a journey learning Rust and Splunk.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Department for Education (Contract)
        link: https://www.education.gov.uk
        link_text: DfE
        sub_title: Cyber Security Engineer
        caption: March 2024 - Present
        quote: >
          The Department for Education is responsible for children's services and education, including early years, schools, higher and further education policy, apprenticeships and wider skills in England.
        description: | # this will include new lines to allow paragraphs
            I have been contracted by the Department for Education to provide guidance on the Secure Software Development Lifecycle, penetration testing, vulnerability management, threat modelling, and security tooling. Key tasks include:

            * helping to develop continuous assurance against common benchmarks in Splunk
            * releasing and packaging [a tool built by the team to package up and release Splunk Apps](https://github.com/DFE-Digital/splunk-app-packager)
            * consulting on Secure by Design processes and the Secure Software Development Lifecycle to help DfE provide security services in support of the [CDDO Secure by Design Principles](https://www.security.gov.uk/policy-and-guidance/secure-by-design/principles/)
            * contributing to the building of [documentation and standards for secure by design](https://github.com/DFE-Digital/secure-by-design-docs)
            * producing threat models and providing assistance on building a threat modelling capability including automated threat models for scalability
            * pen testing applications and infrastructure
            * producing tooling, such as [reusable workflows and templates to assist developers and security professionals in scanning and monitoring for threats with DevSecOps tools (SAST, DAST, SCA)](https://github.com/DFE-Digital/github-actions/blob/master/.github/workflows/reusable-workflow-sast.yml)
            * helping to shape vulnerability management for development and security teams in a scalable way with automation and standards, including [automated security.txt and thanks.txt deployments to Azure with terraform and github actions](https://github.com/dfe-Digital/vulnerability-disclosure-program)
            * building [standards for GitHub](https://technical-guidance.education.gov.uk/standards/storing-source-code/#summary-highlights) and Application Security
            
      - layout: left
        title: NewDay Cards
        link: https://www.newday.co.uk/
        link_text: NewDay
        sub_title: Senior Application Security Engineer
        caption: July 2022 - March 2024
        quote: >
          Helping people move forward with credit.
        description: | # this will include new lines to allow paragraphs
            My position at NewDay helped me to further improve on my learnings from KidsLoop as an appsec engineer. I was a member of a bigger Application Security team and we worked together to improve the security of NewDays applications and infrastructure. This role included:
            
            * leading the roll out of our DAST tool across our estate, inlcuding the PoV, planning automation, fixing bugs, drafting a rollout schedule
            * building and maintaining GitHub Actions templates and composites to deploy tools across the org
            * contributing to application security processes and documentation for pen testing and issue triage
            * organising and scoping pen tests
            * testing for issues and providing remediation assistance
            * providing guidance and assistance to other teams and team members on application security and secure software development
            * organising and running threat models/reviews 
            * scripting and automating to improve processes and provide visibility in response to known issues and incidents
            
      - layout: left
        title: KidsLoop
        link: https://kidsloop.net/
        link_text: KidsLoop
        sub_title: Application Security Consultant
        caption: January 2022 - July 2022
        quote: >
          We aim to transform early years education by providing the tools and asset libraries to digitize content, collect data, and make a personalized learning path for every student.
        description: | # this will include new lines to allow paragraphs
            I began working for KidsLoop as their new Application Security Consultant to help them to test their applications and infrastructure for vulnerabilities and to provide security advice and threat modelling earlier on in the Secure Software Development Lifecycle. This included setting up the new Threat Modelling process as well as working with teams on creating code scanning options in GitHub Actions and providing advice to teams working on new product features. During my time at KidsLoop I worked on:
           
            * developing and running the Threat Modelling process following STRIDE and DREAD
            * pen testing web applications 
            * developing GitHub Actions reusable workflows and templates to scan code/terraform/containers for vulnerabilities
            * automating reporting and scanning with scripts and APIs
            * assisting teams to fix misconfigurations/issues
            * contributing to the internal RFC processes
            * providing security guidance to internal teams
            * auditing EKS Kubernetes environment against CIS benchmarks
            * reviewing AWS environments and testing suspected misconfigurations

      - layout: left
        title: Cabinet Office | CDIO Cyber Security | Government Digital Service (GDS)
        link: www.gov.uk/government/organisations/cabinet-office
        link_text: GOV.UK
        sub_title: Ethical Hacker
        caption: January 2019 - January 2022
        quote: >
          We support the Prime Minister and ensure the effective running of government. We are also the corporate headquarters for government, in partnership with HM Treasury, and we take the lead in certain critical policy areas.
        description: | # this will include new lines to allow paragraphs
            I was first employed by GDS (Government Digital Service) in January 2019 as the sole Ethical Hacker in a multidisciplinary team. The scope of the team later expanded by merging the team into the [Cabinet Office CDIO (Chief Digital Information Office)](https://gds-way.cloudapps.digital/standards/cdio-pillars.html#cdio-security), our responsibilities expanding to the whole of the Cabinet Office, rather than just GDS. I became the technical lead for penetration testing in CDIO; scheduling tests, setting up the end-to-end processes, creating all of the team technical documentation, and leading a small team of testers.
            
            My team currently performs:
            * web application penetration tests
            * AWS security reviews
            * vulnerability scans (including for PCI compliance)
            * terraform code reviews
            * secure code reviews (languages include: Ruby, Python, GoLang, and Java)
            * review of the CI/CD pipelines and secret management
            * internal IT network penetration tests
            * assisting colleagues with finding issues in our SIEM and advising on attack methods
            * developing and editing scripts to improve our processes - examples of which include:
              * an [installed packages CVE evaluation script](https://github.com/pritchyspritch/active-cve-check) that I forked and edited to cut our PCI scanning time down by adding automatic package collection and personalised reporting.
              * a bash [script I hacked together](https://github.com/pritchyspritch/ecr-scanner) to download, build and scan AWS ECR container images with Trivy.

            During my time working with engineers, I also lead the development of our [Nessus scanner running in AWS, deployed by terraform and concourse CI/CD](https://github.com/pritchyspritch/cyber-security-nessus), with all data automatically being sent to Splunk using our in-house log shipping tool.

            All our testing is done via our [Kali Linux testing machines deployed to AWS EC2 with terraform](https://github.com/alphagov/penetration-testing-instance), with our traffic from BurpSuite being tunneled through it also using SSH tunnels.

      - layout: left
        title: Dionach Ltd
        link: www.dionach.com
        link_text: Dionach
        sub_title: Penetration Tester
        caption: September 2016 - January 2019
        quote: >
          Dionach is an independent, CREST approved global provider of information security solutions.
        description: | # this will include new lines to allow paragraphs
            Dionach are a medium sized computer security company based in Oxford. They provide a wide range of security services to the public and private sector.

            Dionach trained me as a penetration tester, during my time with them I:

            * conducted a large number of penetration tests with detailed technical reports
            * had an above average success rate on social engineering campaigns (phishing and physical)
            * learned to use a wide range of security tools
            * learned to conduct tests using manual techniques with a proxy to intercept requests
            * lead the majority of tests but sometimes worked in a team to work on different areas of a larger project
            * carried out a large number of security audits on client sites including IT Health Checks and Cyber Essentials Plus

      - layout: left
        title: Prigital Ltd
        link: www.prigital.co.uk
        link_text: Prigital
        sub_title: Self employed digital services provider / Application Security Consultancy
        caption: August 2019 - May 2020 / March 2024 - Present
        quote: >
          Prigital is a company I set up to allow me to provide web development services to a single client, but has now been repurposed to provide application security consultancy.
        description: | # this will include new lines to allow paragraphs
            Prigital was originally set up to provide digital services to a single client in the shipping industry. I came in halfway through a project to develop it further, bring on a sub-contractor on through my company and manage the delivery.

            Prigital Ltd has since been repurposed to provide Application Security Constultancy and Engineering services.


  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of West London
        caption: 2012 - 2016
        sub_title: BSc (Hons) Computing Science - 1st Class
        quote: >
          The University of West London is a public research university in the United Kingdom which has campuses in Ealing and Brentford in Greater London, as well as in Reading, Berkshire. The university has roots back to 1860, when the Lady Byron School was founded, which later became Ealing College of Higher Education.
        description: | # this will include new lines to allow paragraphs
          During my time at UWL, I learned the basics of computing and programming. It was in my security module, however, that I learned about the different career opportunities available in cyber security.

          My dissertation was on Blockchain and Accounting Software Usability.

          Our modules includes:
          - Algorithms and Data Structures
          - Database Design and Management
          - Computer Security
          - Distributed Systems
          - Internet Technologies
          - Knowledge Based Systems
          - Object Oriented Modelling and Programming.
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
